version: "2.2"
services:

  document_indexer:
    image: curlimages/curl
    networks:
      - elastic
    volumes:
      - ./test.json:/usr/share/documents/documents_bulk_elasicsearch.json
    command: ['curl', 
    '-XPUT', 'es01:9200/_bulk', 
    '-X', 'Content-Type: application/x-ndjson', 
    '--data-binary', '@/usr/share/documents/documents_bulk_elasicsearch.json']

networks:
  elastic:
    external: true
