version: "3.7"
services:
  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile_elasticsearch
    container_name: news_articles_elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - elastic_net

  kibana:
    container_name: news_articles_kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      - "ELASTICSEARCH_HOSTS=http://news_articles_elasticsearch:9200"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic_net

  nginx:
    image: nginx
    ports:
      - 8200:80
    networks:
      - elastic_net
    volumes:
      - ./elasticsearch/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  elastic_data:

networks:
  elastic_net:
