version: "2.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: news_articles_elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasicsearch.yml
    ports:
      - "9200:9200"
    networks:
      - local

  kibana:
    container_name: news_articles_kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      - "ELASTICSEARCH_HOSTS=http://news_articles_elasticsearch:9200"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - local

volumes:
  elasticdata:

networks:
  local:
    driver: bridge
